#!/bin/sh

set -e

echo "Running prettier"
npx prettier --check .

echo "Running eslint"
npx eslint --max-warnings=0 --ext .js,.cjs,.mjs,.jsx,.ts,.tsx .

echo "Running package.json formatter"
node scripts/format-package-json.js
